// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4uOVaxiikCCJA3da3HiEKiOHT-IRjIDo',
    appId: '1:906010572934:web:16e4f17092e4c43780b907',
    messagingSenderId: '906010572934',
    projectId: 'chat-app-4f70e',
    authDomain: 'chat-app-4f70e.firebaseapp.com',
    storageBucket: 'chat-app-4f70e.firebasestorage.app',
    measurementId: 'G-GB790R2VG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJI5PDq4rYvgQRiyxPSDjDyA7IPi21oZE',
    appId: '1:906010572934:android:9d5f68824e3665a280b907',
    messagingSenderId: '906010572934',
    projectId: 'chat-app-4f70e',
    storageBucket: 'chat-app-4f70e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcE0iNmHa5G3kD-Eh49sJKCWSAv0slGYo',
    appId: '1:906010572934:ios:effd4a1334b77af780b907',
    messagingSenderId: '906010572934',
    projectId: 'chat-app-4f70e',
    storageBucket: 'chat-app-4f70e.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcE0iNmHa5G3kD-Eh49sJKCWSAv0slGYo',
    appId: '1:906010572934:ios:effd4a1334b77af780b907',
    messagingSenderId: '906010572934',
    projectId: 'chat-app-4f70e',
    storageBucket: 'chat-app-4f70e.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4uOVaxiikCCJA3da3HiEKiOHT-IRjIDo',
    appId: '1:906010572934:web:d094714f2ff6f29e80b907',
    messagingSenderId: '906010572934',
    projectId: 'chat-app-4f70e',
    authDomain: 'chat-app-4f70e.firebaseapp.com',
    storageBucket: 'chat-app-4f70e.firebasestorage.app',
    measurementId: 'G-5KJWFR1LPB',
  );
}
