name: websocket_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  firebase_core: ^2.7.0
  firebase_auth: ^4.5.0
  web_socket_channel: ^2.2.0
  lints: ^5.0.0
  test: ^1.24.0
